/**
 * animation.js - Natural Insect Idle Animation Controller
 * Implements subtle, realistic bio-mimetic idle behaviors for grasshoppers:
 * - Segmented antennae micro-twitching and wave swaying
 * - Cervical head tilting and palp sensory twitching
 * - Rhythmic abdominal tracheal respiration pumping
 * - Subtle postural weight shifts
 */

export class LocustAnimator {
  constructor() {
    this.speedMultiplier = 1.0;
    this.isPaused = false;
    this.twitchTimer = 0;
    this.nextTwitchTime = 2.5;
    this.twitchActive = false;
    this.twitchSide = 1;
    this.twitchProgress = 0;
  }

  /**
   * Sets animation playback speed.
   * @param {number} speed - 1.0 = normal, 0.4 = slow-motion, 0.0 = paused
   */
  setSpeed(speed) {
    this.speedMultiplier = speed;
  }

  setPaused(paused) {
    this.isPaused = paused;
  }

  /**
   * Updates all bio-idle motions on a locust model.
   * @param {THREE.Group} locust - The locust model generated by LocustBuilder
   * @param {number} time - Elapsed time in seconds
   * @param {number} delta - Frame delta time in seconds
   */
  update(locust, time, delta) {
    if (this.isPaused || this.speedMultiplier <= 0) return;

    const t = time * this.speedMultiplier;
    const joints = locust.userData.joints;
    if (!joints) return;

    // ----------------------------------------------------
    // 1. Antennae Sensory Motions
    // ----------------------------------------------------
    // Random twitch trigger every 2 to 4 seconds
    this.twitchTimer += delta * this.speedMultiplier;
    if (this.twitchTimer > this.nextTwitchTime) {
      this.twitchActive = true;
      this.twitchProgress = 0;
      this.twitchSide = Math.random() < 0.5 ? 1 : -1;
      this.twitchTimer = 0;
      this.nextTwitchTime = 2.0 + Math.random() * 3.0;
    }

    let twitchOffset = 0;
    if (this.twitchActive) {
      this.twitchProgress += delta * 12; // Fast snap
      if (this.twitchProgress < Math.PI) {
        twitchOffset = Math.sin(this.twitchProgress) * 0.28;
      } else {
        this.twitchActive = false;
      }
    }

    // Left Antenna
    if (joints.leftAntenna) {
      const baseWaveL = Math.sin(t * 1.2) * 0.08 + Math.cos(t * 0.6) * 0.05;
      const twitchL = (this.twitchSide === 1) ? twitchOffset : 0;
      joints.leftAntenna.root.rotation.x = 0.5 + baseWaveL + twitchL * 0.8;
      joints.leftAntenna.root.rotation.z = 0.2 + Math.sin(t * 1.5) * 0.06 + twitchL * 0.4;

      // Propagate wave along chain nodes
      joints.leftAntenna.nodes.forEach((node, idx) => {
        const factor = (idx + 1) * 0.015;
        node.rotation.x = Math.sin(t * 2.2 - idx * 0.4) * factor + (twitchL * factor * 2.5);
        node.rotation.z = Math.cos(t * 1.8 - idx * 0.3) * factor;
      });
    }

    // Right Antenna
    if (joints.rightAntenna) {
      const baseWaveR = Math.sin(t * 1.1 + 1.2) * 0.08 + Math.cos(t * 0.7) * 0.05;
      const twitchR = (this.twitchSide === -1) ? twitchOffset : 0;
      joints.rightAntenna.root.rotation.x = 0.5 + baseWaveR + twitchR * 0.8;
      joints.rightAntenna.root.rotation.z = -0.2 - Math.sin(t * 1.4 + 0.8) * 0.06 - twitchR * 0.4;

      joints.rightAntenna.nodes.forEach((node, idx) => {
        const factor = (idx + 1) * 0.015;
        node.rotation.x = Math.sin(t * 2.0 - idx * 0.4 + 1.5) * factor + (twitchR * factor * 2.5);
        node.rotation.z = -Math.cos(t * 1.9 - idx * 0.3 + 0.7) * factor;
      });
    }

    // ----------------------------------------------------
    // 2. Neck & Head Tilting (首関節・頭部)
    // ----------------------------------------------------
    if (joints.neck) {
      // Gentle breathing pitch and inquisitive yaw
      const headPitch = Math.sin(t * 0.75) * 0.035 + Math.sin(t * 0.25) * 0.02;
      const headYaw = Math.cos(t * 0.45) * 0.04;
      const headRoll = Math.sin(t * 0.35) * 0.015;
      joints.neck.rotation.set(headPitch, headYaw, headRoll);
    }

    // ----------------------------------------------------
    // 3. Maxillary Palps Sensory Twitch (口元の小腮鬚)
    // ----------------------------------------------------
    if (joints.leftPalp && joints.rightPalp) {
      const palpFlick = Math.sin(t * 6.5) * 0.12 * (Math.sin(t * 1.2) > 0 ? 1 : 0.2);
      joints.leftPalp.rotation.x = palpFlick;
      joints.rightPalp.rotation.x = -palpFlick;
    }

    // ----------------------------------------------------
    // 4. Abdominal Tracheal Respiration (腹部呼吸ポンピング)
    // ----------------------------------------------------
    if (joints.abdomen) {
      // Insect respiratory pumping occurs at ~0.6 Hz
      const respPhase = Math.sin(t * 3.2);
      const respScaleY = 1.0 + respPhase * 0.038; // Expansion & contraction
      const respScaleZ = 1.0 + respPhase * 0.015;

      joints.abdomen.scale.set(1.0, respScaleY, respScaleZ);

      // Metameric ripple across abdominal segments
      if (joints.abdomenNodes) {
        joints.abdomenNodes.forEach((node, idx) => {
          const segPhase = Math.sin(t * 3.2 - idx * 0.25);
          node.position.y = -0.01 * idx + segPhase * 0.008;
        });
      }
    }

    // ----------------------------------------------------
    // 5. Hind Legs Micro Postural Sway (膝の微細な重心移動)
    // ----------------------------------------------------
    if (joints.leftHindLeg && joints.rightHindLeg) {
      const sway = Math.sin(t * 0.8) * 0.015;
      const basePitch = -Math.PI * 0.28;
      joints.leftHindLeg.femur.rotation.x = basePitch + sway;
      joints.rightHindLeg.femur.rotation.x = basePitch - sway;
    }
  }
}
